from tkinter import *
from tkinter import ttk
fp = Tk()   # fenetre principale
fp.geometry("480x400")
fp.title("Timer TMR2")
label1 = Label(fp,text='Fosc en MHz')
label1.place(x=10, y=30, anchor=SW)
edit1 = Entry(fp)
edit1.place(x=10, y=30, anchor=NW)
label2 = Label(fp,text='Période en µs')
label2.place(x=10, y=80, anchor=SW)
edit2 = Entry(fp)
edit2.place(x=10, y=80, anchor=NW)
label3 = Label(fp,text='Tolérence en µs')
label3.place(x=10, y=130, anchor=SW)
edit3 = Entry(fp)
edit3.place(x=10, y=130, anchor=NW)
go_button = ttk.Button(fp,text = "GO")
go_button.place(x=10,y=200)
exit_button = ttk.Button(fp,text = "Exit",command = fp.destroy)
exit_button.place(x=10,y=300)
label4 = Label(fp,font='TkFixedFont',text=' CTR  PREDIV  PR2+1  POSTDIV  T  Erreur')
label4.place(x=150, y=30, anchor=SW)
fen4 = Text(fp)
fen4.place(x = 150,y = 30, anchor=NW , relwidth=0.65, relheight=0.9)
fp.mainloop() 
